# Generated by Django 2.1 on 2019-03-12 10:09

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Awards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('is_active', models.BooleanField(default=False)),
                ('frequency', models.CharField(choices=[('MONTHLY', 'Monthly'), ('QUATERLY', 'Quaterly'), ('YEARLY', 'Yearly')], max_length=10)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'awards',
            },
        ),
        migrations.CreateModel(
            name='AwardTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(max_length=150)),
                ('is_active', models.BooleanField(default=False)),
                ('award', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nominate_app.Awards')),
            ],
            options={
                'db_table': 'award_templates',
            },
        ),
        migrations.CreateModel(
            name='NominationAnswers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_option', models.BooleanField(blank=True, max_length=20, null=True)),
                ('answer_text', models.CharField(blank=True, max_length=500, null=True)),
                ('attachment_path', models.FileField(blank=True, max_length=500, null=True, upload_to='')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('award_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nominate_app.AwardTemplate')),
            ],
            options={
                'db_table': 'nomination_answers',
            },
        ),
        migrations.CreateModel(
            name='NominationChain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewed_at', models.DateField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'nomination_chains',
            },
        ),
        migrations.CreateModel(
            name='NominationInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='new', max_length=50)),
                ('result', models.CharField(blank=True, max_length=50, null=True)),
                ('award_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nominate_app.AwardTemplate')),
            ],
            options={
                'db_table': 'nomination_instances',
            },
        ),
        migrations.CreateModel(
            name='NominationPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_day', models.DateField(max_length=20)),
                ('end_day', models.DateField(max_length=20)),
                ('award', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nominate_app.Awards')),
            ],
            options={
                'db_table': 'nomination_periods',
            },
        ),
        migrations.CreateModel(
            name='NominationPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(max_length=20)),
                ('end_date', models.DateField(max_length=20)),
            ],
            options={
                'db_table': 'nomination_plans',
            },
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qname', models.CharField(max_length=100)),
                ('qtype', models.CharField(choices=[('SUBJECTIVE', 'subjective'), ('OBJECTIVE', 'objective')], default='subjective', max_length=100)),
                ('attachment_need', models.BooleanField(default=False)),
                ('award_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nominate_app.AwardTemplate')),
            ],
            options={
                'db_table': 'award_questions',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('group', models.CharField(choices=[('level1', 'level1'), ('level2', 'level2'), ('level3', 'level3')], max_length=7)),
            ],
            options={
                'db_table': 'roles',
            },
        ),
        migrations.CreateModel(
            name='User_Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nominate_app.Role')),
            ],
            options={
                'db_table': 'user_role',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=70, unique=True)),
                ('designation', models.CharField(max_length=70)),
                ('telephonenumber', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('employeenumber', models.CharField(max_length=70)),
                ('jobtitle', models.CharField(max_length=70)),
                ('cn', models.CharField(max_length=70)),
                ('title', models.CharField(max_length=70)),
                ('lastpwdchange', models.CharField(max_length=70)),
                ('lastname', models.CharField(max_length=70)),
                ('defaultpwd', models.CharField(max_length=70)),
                ('baselocation', models.CharField(max_length=70)),
                ('uid', models.CharField(max_length=70)),
                ('worklocation', models.CharField(max_length=70)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_profiles',
            },
        ),
        migrations.AddField(
            model_name='user_role',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nominate_app.UserProfile'),
        ),
        migrations.AddField(
            model_name='questions',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nominate_app.Role'),
        ),
        migrations.AddField(
            model_name='nominationplan',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nominate_app.Role'),
        ),
        migrations.AddField(
            model_name='nominationplan',
            name='nomination_period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nominate_app.NominationPeriod'),
        ),
        migrations.AddField(
            model_name='nominationperiod',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nominate_app.Role'),
        ),
        migrations.AddField(
            model_name='nominationinstance',
            name='nomination_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nominate_app.NominationPlan'),
        ),
        migrations.AddField(
            model_name='nominationinstance',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='nominationchain',
            name='nomination_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nominate_app.NominationInstance'),
        ),
        migrations.AddField(
            model_name='nominationchain',
            name='reviewer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='nominationanswers',
            name='nomination_chain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nominate_app.NominationChain'),
        ),
        migrations.AddField(
            model_name='nominationanswers',
            name='nomination_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nominate_app.NominationInstance'),
        ),
        migrations.AddField(
            model_name='nominationanswers',
            name='question_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nominate_app.Questions'),
        ),
        migrations.AddField(
            model_name='nominationanswers',
            name='submitted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
