# Generated by Django 2.1 on 2019-03-14 07:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nominate_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NominationPeriodFrequency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_day', models.DateField(max_length=20)),
                ('end_day', models.DateField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'nomination_period_frequency',
            },
        ),
        migrations.CreateModel(
            name='NominationSubmitter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewed_at', models.DateField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'nomination_submitters',
            },
        ),
        migrations.CreateModel(
            name='NominationTimeSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_day', models.DateField(max_length=20)),
                ('end_day', models.DateField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'nomination_time_slots',
            },
        ),
        migrations.RenameModel(
            old_name='User_Role',
            new_name='UserRole',
        ),
        migrations.RemoveField(
            model_name='nominationchain',
            name='nomination_instance',
        ),
        migrations.RemoveField(
            model_name='nominationchain',
            name='reviewer_id',
        ),
        migrations.RenameField(
            model_name='nominationanswers',
            old_name='question_id',
            new_name='question',
        ),
        migrations.RemoveField(
            model_name='nominationinstance',
            name='nomination_plan',
        ),
        migrations.RemoveField(
            model_name='nominationinstance',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='lastname',
        ),
        migrations.AddField(
            model_name='awards',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='awardtemplate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='nominationanswers',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='nominationinstance',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='nominationperiod',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='nominationperiod',
            name='is_template',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='nominationplan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='questions',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='nominationanswers',
            name='attachment_path',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='answers/images'),
        ),
        migrations.AlterField(
            model_name='nominationanswers',
            name='nomination_chain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nominate_app.NominationSubmitter'),
        ),
        migrations.AlterField(
            model_name='role',
            name='group',
            field=models.CharField(choices=[('level0', 'level0'), ('level1', 'level1'), ('level2', 'level2'), ('level3', 'level3')], max_length=7),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='userrole',
            table='user_roles',
        ),
        migrations.DeleteModel(
            name='NominationChain',
        ),
        migrations.AddField(
            model_name='nominationtimeslot',
            name='award',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nominate_app.Awards'),
        ),
        migrations.AddField(
            model_name='nominationtimeslot',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nominate_app.Role'),
        ),
        migrations.AddField(
            model_name='nominationtimeslot',
            name='nomination_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nominate_app.NominationInstance'),
        ),
        migrations.AddField(
            model_name='nominationsubmitter',
            name='nomination_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nominate_app.NominationInstance'),
        ),
        migrations.AddField(
            model_name='nominationsubmitter',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='nominationperiodfrequency',
            name='award',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nominate_app.Awards'),
        ),
        migrations.AddField(
            model_name='nominationperiodfrequency',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nominate_app.Role'),
        ),
    ]
