# Generated by Django 2.1 on 2019-07-30 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nominate_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nominationperiod',
            old_name='level',
            new_name='group',
        ),
    ]
