# Generated by Django 2.1 on 2019-07-31 05:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nominate_app', '0002_auto_20190730_0752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nominationinstance',
            name='status',
            field=models.IntegerField(choices=[('New', 0), ('Saved', 1), ('Submitted', 2), ('Reviewed', 3), ('Approved', 4), ('Dismissed', 5), ('On hold', 6)], default=0),
        ),
        migrations.AlterField(
            model_name='nominationinstance',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
