# Generated by Django 2.1 on 2019-03-12 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nominate_app', '0002_auto_20190312_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='group',
            field=models.CharField(choices=[('level0', 'level0'), ('level1', 'level1'), ('level2', 'level2'), ('level3', 'level3')], max_length=7),
        ),
    ]
