# Generated by Django 2.1 on 2019-03-15 06:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nominate_app', '0002_auto_20190314_0708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nominationplan',
            name='level',
        ),
        migrations.RemoveField(
            model_name='nominationplan',
            name='nomination_period',
        ),
        migrations.AddField(
            model_name='nominationinstance',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='NominationPlan',
        ),
    ]
