# Generated by Django 2.1 on 2019-02-19 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nominate_app', '0002_auto_20190219_0930'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='awards',
            table='awards',
        ),
        migrations.AlterModelTable(
            name='awardtemplate',
            table='award_templates',
        ),
        migrations.AlterModelTable(
            name='nominationperiod',
            table='nomination_periods',
        ),
        migrations.AlterModelTable(
            name='questions',
            table='award_questions',
        ),
        migrations.AlterModelTable(
            name='role',
            table='roles',
        ),
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
    ]
