# Generated by Django 2.1 on 2019-07-24 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nominate_app', '0002_comment'),
        ('nominate_app', '0002_auto_20190723_0724'),
    ]

    operations = [
    ]
