# Generated by Django 2.1 on 2019-02-20 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nominate_app', '0003_auto_20190219_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='awardtemplate',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
