# Generated by Django 2.2.3 on 2019-07-24 12:28

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nominate_app', '0003_auto_20190724_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='options',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), default=list, size=20),
        ),
    ]
