# Generated by Django 2.1 on 2019-03-12 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nominate_app', '0004_auto_20190312_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(default='test@test.com', max_length=70, unique=True),
            preserve_default=False,
        ),
    ]
