# Generated by Django 2.2.3 on 2019-07-25 07:18

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nominate_app', '0004_questions_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='options',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), blank=True, null=True, size=22),
        ),
    ]
