# Generated by Django 2.1 on 2019-02-20 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nominate_app', '0004_awardtemplate_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='group',
            field=models.CharField(choices=[('level1', 'level1'), ('level2', 'level2'), ('level3', 'level3')], max_length=7),
        ),
    ]
