# Generated by Django 2.1 on 2019-02-21 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nominate_app', '0004_auto_20190220_0737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awards',
            name='frequency',
            field=models.CharField(blank=True, choices=[('M', 'Monthly'), ('Q', 'Quaterly'), ('Y', 'Yearly')], max_length=3),
        ),
    ]
