# Generated by Django 2.1 on 2019-02-25 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nominate_app', '0005_auto_20190220_0730'),
        ('nominate_app', '0005_auto_20190221_1235'),
    ]

    operations = [
    ]
