# Generated by Django 2.1 on 2019-07-25 06:52

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nominate_app', '0003_merge_20190724_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='options',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), blank=True, null=True, size=20),
        ),
    ]
