# Generated by Django 2.2.3 on 2019-07-26 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nominate_app', '0006_questions_options'),
        ('nominate_app', '0005_auto_20190725_0718'),
    ]

    operations = [
    ]
