# Generated by Django 2.1 on 2019-02-25 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nominate_app', '0006_merge_20190222_0908'),
        ('nominate_app', '0007_auto_20190225_0521'),
    ]

    operations = [
    ]
