# Generated by Django 2.1 on 2019-02-25 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nominate_app', '0008_merge_20190225_0729'),
        ('nominate_app', '0008_auto_20190225_0738'),
    ]

    operations = [
    ]
