# Generated by Django 2.1 on 2019-02-26 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nominate_app', '0012_auto_20190225_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awards',
            name='frequency',
            field=models.CharField(choices=[('MONTHLY', 'Monthly'), ('QUATERLY', 'Quaterly'), ('YEARLY', 'Yearly')], max_length=10),
        ),
        migrations.AlterField(
            model_name='questions',
            name='qtype',
            field=models.CharField(choices=[('SUBJECTIVE', 'subjective'), ('OBJECTIVE', 'objective')], max_length=20),
        ),
    ]
