# Generated by Django 2.1 on 2019-02-27 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nominate_app', '0013_auto_20190226_0852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awardtemplate',
            name='template_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='questions',
            name='qtype',
            field=models.CharField(choices=[('SUBJECTIVE', 'subjective'), ('OBJECTIVE', 'objective')], max_length=100),
        ),
    ]
