# Generated by Django 2.1 on 2019-02-28 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nominate_app', '0014_auto_20190227_0522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='qtype',
            field=models.CharField(choices=[('SUBJECTIVE', 'subjective'), ('OBJECTIVE', 'objective')], default='subjective', max_length=100),
        ),
    ]
