# Generated by Django 2.1 on 2019-03-04 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nominate_app', '0015_auto_20190228_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nominationperiod',
            name='end_day',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='nominationperiod',
            name='start_day',
            field=models.DateField(),
        ),
    ]
