# Generated by Django 2.1 on 2019-03-06 07:05

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nominate_app', '0015_auto_20190228_1319'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=70, unique=True)),
                ('designation', models.CharField(max_length=70)),
                ('telephonenumber', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('employeenumber', models.CharField(max_length=70)),
                ('jobtitle', models.CharField(max_length=70)),
                ('cn', models.CharField(max_length=70)),
                ('title', models.CharField(max_length=70)),
                ('lastpwdchange', models.CharField(max_length=70)),
                ('lastname', models.CharField(max_length=70)),
                ('defaultpwd', models.CharField(max_length=70)),
                ('baselocation', models.CharField(max_length=70)),
                ('uid', models.CharField(max_length=70)),
                ('worklocation', models.CharField(max_length=70)),
            ],
            options={
                'db_table': 'user_profiles',
            },
        ),
        migrations.AlterField(
            model_name='user_role',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nominate_app.UserProfile'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
