# Generated by Django 2.1 on 2019-03-05 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nominate_app', '0016_auto_20190304_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nominationinstance',
            name='result',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='nominationinstance',
            name='status',
            field=models.CharField(default='new', max_length=50),
        ),
    ]
