# Generated by Django 2.1 on 2019-03-07 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nominate_app', '0016_auto_20190304_1017'),
        ('nominate_app', '0016_auto_20190304_0926'),
    ]

    operations = [
    ]
