# Generated by Django 2.1 on 2019-03-05 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nominate_app', '0016_auto_20190304_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nominationchain',
            name='reviewed_at',
            field=models.DateField(blank=True, max_length=20, null=True),
        ),
    ]
