# Generated by Django 2.1 on 2019-03-05 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nominate_app', '0017_auto_20190305_0616'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment_path', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'answer_attachments',
            },
        ),
        migrations.CreateModel(
            name='NominationAnswers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_option', models.BooleanField(blank=True, max_length=20, null=True)),
                ('answer_text', models.CharField(blank=True, max_length=500, null=True)),
                ('award_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nominate_app.AwardTemplate')),
                ('nomination_chain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nominate_app.NominationChain')),
                ('nomination_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nominate_app.NominationInstance')),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nominate_app.Questions')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nominate_app.User')),
            ],
            options={
                'db_table': 'nomination_answers',
            },
        ),
        migrations.AddField(
            model_name='answerattachment',
            name='answer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nominate_app.NominationAnswers'),
        ),
    ]
