# Generated by Django 2.1 on 2019-03-07 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nominate_app', '0017_merge_20190307_0608'),
        ('nominate_app', '0018_auto_20190305_1212'),
    ]

    operations = [
    ]
