# Generated by Django 2.1 on 2019-03-11 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nominate_app', '0019_merge_20190307_1045'),
        ('nominate_app', '0017_auto_20190305_1031'),
    ]

    operations = [
    ]
