# Generated by Django 2.1 on 2019-03-07 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nominate_app', '0020_auto_20190307_1024'),
        ('nominate_app', '0019_merge_20190307_1045'),
    ]

    operations = [
    ]
