# Generated by Django 2.1 on 2019-03-12 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nominate_app', '0020_merge_20190311_1053'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NominationChain',
            new_name='NominationSubmitter',
        ),
        migrations.AlterField(
            model_name='nominationperiod',
            name='end_day',
            field=models.DateField(max_length=20),
        ),
        migrations.AlterField(
            model_name='nominationperiod',
            name='start_day',
            field=models.DateField(max_length=20),
        ),
    ]
