# Generated by Django 2.1 on 2019-03-12 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nominate_app', '0021_auto_20190312_0741'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User_Role',
            new_name='UserRole',
        ),
    ]
