# Generated by Django 2.1 on 2019-03-07 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nominate_app', '0021_merge_20190307_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nominationperiod',
            name='end_day',
            field=models.DateField(max_length=20),
        ),
        migrations.AlterField(
            model_name='nominationperiod',
            name='start_day',
            field=models.DateField(max_length=20),
        ),
    ]
