# Generated by Django 2.1 on 2019-03-08 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nominate_app', '0022_auto_20190307_1139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answerattachment',
            name='answer_id',
        ),
        migrations.RemoveField(
            model_name='answerattachment',
            name='question_id',
        ),
        migrations.AddField(
            model_name='nominationanswers',
            name='attachment_path',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='nominationanswers',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.DeleteModel(
            name='AnswerAttachment',
        ),
    ]
