# Generated by Django 2.1 on 2019-03-13 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nominate_app', '0023_auto_20190312_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='nominationperiod',
            name='is_template',
            field=models.BooleanField(default=False),
        ),
    ]
