# Generated by Django 2.1 on 2019-03-11 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nominate_app', '0017_auto_20190305_1031'),
        ('nominate_app', '0024_auto_20190308_1048'),
    ]

    operations = [
    ]
