# Generated by Django 2.1 on 2019-03-13 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nominate_app', '0024_nominationperiod_is_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='NominationPeriodFrequency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_day', models.DateField(max_length=20)),
                ('end_day', models.DateField(max_length=20)),
                ('award', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nominate_app.Awards')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nominate_app.Role')),
            ],
            options={
                'db_table': 'nomination_period_frequency',
            },
        ),
    ]
