# Generated by Django 2.1 on 2019-03-11 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nominate_app', '0025_merge_20190311_0946'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nominationanswers',
            old_name='question_id',
            new_name='question',
        ),
        migrations.AlterField(
            model_name='nominationanswers',
            name='attachment_path',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='answers/images'),
        ),
    ]
