# Generated by Django 2.1 on 2019-03-13 06:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('nominate_app', '0025_nominationperiodfrequency'),
    ]

    operations = [
        migrations.AddField(
            model_name='nominationperiodfrequency',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nominationperiodfrequency',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
