# Generated by Django 2.1 on 2019-03-13 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nominate_app', '0027_nominationtimeslot'),
    ]

    operations = [
        migrations.AddField(
            model_name='nominationtimeslot',
            name='nomination_instance',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='nominate_app.NominationInstance'),
            preserve_default=False,
        ),
    ]
