# Generated by Django 2.1 on 2019-03-13 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nominate_app', '0028_nominationtimeslot_nomination_instance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nominationinstance',
            name='user',
        ),
    ]
