# Generated by Django 2.1 on 2019-03-13 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nominate_app', '0029_remove_nominationinstance_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nominationinstance',
            name='nomination_period',
        ),
    ]
