# Generated by Django 2.1 on 2019-03-13 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nominate_app', '0030_remove_nominationinstance_nomination_period'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nominationsubmitter',
            old_name='reviewer_id',
            new_name='reviewer',
        ),
    ]
